# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'final_sys_test.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import time
import json
from PyQt5 import QtCore, QtGui, QtWidgets
import os
import requests


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1374, 768)
        MainWindow.setStyleSheet("background-color:#ffffff\n"
"\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(290, 50, 901, 71))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setStyleSheet("color:#ffffff;\n"
"font-family: Arial, Helvetica, sans-serif;\n"
"border-radius :15px;\n"
"background-color:#FFE177;")
        self.label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(440, 140, 591, 71))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color:#ffffff;\n"
"font-family: Arial, Helvetica, sans-serif;\n"
"border-radius :15px;\n"
"background-color:#FFE177;")
        self.label_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName("label_3")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(550, 540, 381, 61))
        self.pushButton_5.clicked.connect(self.startTest)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setStyleSheet("color:#ffffff;\n"
"font-family: Arial, Helvetica, sans-serif;\n"
"border-radius :15px;\n"
"background-color:#AEF3C4;")
        self.pushButton_5.setObjectName("pushButton_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(510, 200, 471, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color:#ffffff;\n"
"font-family: Arial, Helvetica, sans-serif;\n"
"border-radius :15px;\n"
"background-color:#FFE177;")
        self.label_6.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setWordWrap(True)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(520, 130, 401, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color:#ffffff;\n"
"font-family: Arial, Helvetica, sans-serif;\n"
"border-radius :15px;\n"
"background-color:#FFE177;")
        self.label_7.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setWordWrap(True)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(470, 270, 541, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color:#ffffff;\n"
"font-family: Arial, Helvetica, sans-serif;\n"
"border-radius :15px;\n"
"background-color:#FFE177;")
        self.label_8.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setWordWrap(True)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(500, 50, 481, 81))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("color:#ffffff;\n"
"font-family: Arial, Helvetica, sans-serif;\n"
"border-radius :15px;\n"
"background-color:#FFE177;")
        self.label_9.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setWordWrap(True)
        self.label_9.setObjectName("label_9")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(170, 460, 1141, 41))
        self.progressBar.setStyleSheet("QProgressBar\n"
"{\n"
"border: solid grey;\n"
"border-radius: 15px;\n"
"color: black;\n"
"}\n"
"QProgressBar::chunk \n"
"{\n"
"background-color: #05B8CC;\n"
"border-radius :15px;\n"
"}      ")
        self.progressBar.setProperty("value", 5)
        self.progressBar.setTextVisible(False)
        self.progressBar.setObjectName("progressBar")
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(460, 630, 561, 61))
        self.pushButton_6.clicked.connect(self.skipTest)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setStyleSheet("color:#ffffff;\n"
"font-family: Arial, Helvetica, sans-serif;\n"
"border-radius :15px;\n"
"background-color:#AEF3C4;")
        self.pushButton_6.setObjectName("pushButton_6")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(520, 340, 441, 71))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("Breath(1).png"))
        self.label_2.setObjectName("label_2")
        self.label_3.raise_()
        self.label.raise_()
        self.pushButton_5.raise_()
        self.progressBar.raise_()
        self.pushButton_6.raise_()
        self.label_2.raise_()
        self.label_8.raise_()
        self.label_6.raise_()
        self.label_7.raise_()
        self.label_9.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1374, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "System Test"))
        self.label.setText(_translate("MainWindow", "        Make sure that no patient is connected during the system test !!"))
        self.label_3.setText(_translate("MainWindow", "Prepare the device,close the y-piece"))
        self.pushButton_5.setText(_translate("MainWindow", "Start Test"))
        self.label_6.setText(_translate("MainWindow", "Resistance: 2.0 [cmH2O/(l/s)]"))
        self.label_7.setText(_translate("MainWindow", "Compliance: 0.8 [ml/cmH2O]"))
        self.label_8.setText(_translate("MainWindow", "Leakage: 11 [ml/min].”"))
        self.label_9.setText(_translate("MainWindow", "Open Y-connector"))
        self.pushButton_6.setText(_translate("MainWindow", "Go To Dashboard"))
        hide=1
        if hide==1 :
             #self.label_5.hide()
             self.label_6.hide()
             self.label_7.hide()
             self.label_8.hide()
             self.label_9.hide()
    def skipTest(self) :
          os.system('final_standby.py')  
          #time.sleep(4)
          #Ui_MainWindow.close()       
    def startTest(self):
        # hide make sure message
        self.label.setHidden(True)
        self.label_3.setHidden(True)
        self.label_9.setHidden(False)
        self.label_9.setText("System test running , Open Y-connector")
        self.pushButton_5.setEnabled(False)#disable button
        
        t=10
        progress=10
        response = requests.get('http://192.168.125.150:8000/test')
        while t>0:    
             self.progressBar.setProperty("value", progress)
             time.sleep(1)
             t -= 1
             progress+=10
        self.label_9.setHidden(True)
        #self.label_5.setHidden(False)
        self.label_6.setHidden(False)
        self.label_7.setHidden(False)
        self.label_8.setHidden(False)
        if 200 <= response.status_code < 300: 
         data=response.json()
         #self.label_9.setText( "System test OK")
         self.label_6.setText("Resistance: " + data['resistance'] + "cmH2O/(l/s)")
         self.label_7.setText("Compliance: " + data['compliance'] + "ml/cmH2O")
         self.label_8.setText("Leakage: " + data['leakage'] + "ml/min")
        else:
         self.label_9.setHidden(False)
         self.label_9.setText( "System test Not OK , Restart Test")
        time.sleep(2)
        #os.system('final_standby.py')
        #self.close()

      
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
